import type { BrowserContext } from '@playwright/test';

export type DirectoryFixture = {
  label: string;
  count?: number;
  metadataOnly?: boolean;
  files?: Array<{ name: string; bytes: number; seed: number }>;
  /** Folders inside this one, to any depth: a real tree, each named by its `label`. */
  folders?: DirectoryFixture[];
};

/** Picker replacement exists only in the runner. No application hooks or auth bypass. */
export async function installDirectories(context: BrowserContext, directories: DirectoryFixture[], png: string) {
  await context.addInitScript(({ directories, png }) => {
    const state = { next: 0, metadataReads: 0, materializedBytes: 0, workers: 0, maxWorkers: 0, workerUrls: [] as string[] };
    Object.assign(window, { __directoryFixture: state });
    const NativeWorker = window.Worker;
    window.Worker = class extends NativeWorker {
      private ended = false;
      constructor(url: string | URL, options?: WorkerOptions) {
        super(url, options);
        state.workers++; state.maxWorkers = Math.max(state.maxWorkers, state.workers);
        state.workerUrls.push(String(url));
      }
      terminate() { if (!this.ended) { state.workers--; this.ended = true; } super.terminate(); }
    };
    const header = Uint8Array.from(atob(png), char => char.charCodeAt(0));
    // A folder holds folders, so the handle's type names itself; TypeScript cannot infer that.
    type FolderHandle = { kind: string; name: string; queryPermission(): Promise<PermissionState>; requestPermission(): Promise<PermissionState>;
      grant(): void; values(): AsyncGenerator<unknown>; getFileHandle(name: string): Promise<unknown>; getDirectoryHandle(name: string): Promise<FolderHandle> };
    // One permission per picked folder, shared by every folder inside it, as the browser does.
    const createDirectory = (definition: DirectoryFixture, permission: { state: PermissionState } = { state: 'prompt' }): FolderHandle => {
      const count = definition.count ?? definition.files?.length ?? 0;
      const descriptor = (index: number) => definition.files?.[index] ?? {
        name: `photo-${String(index).padStart(6, '0')}.jpg`, bytes: 2 * 1024 * 1024, seed: index,
      };
      const fileHandle = (index: number) => {
        const file = descriptor(index);
        return {
          kind: 'file', name: file.name,
          async getFile() {
            if (permission.state !== 'granted') throw new DOMException('Directory permission lost', 'NotAllowedError');
            state.metadataReads++;
            if (definition.metadataOnly) return {
              name: file.name, size: file.bytes, type: 'image/jpeg', lastModified: 1_700_000_000_000,
              arrayBuffer() { throw new Error('Synthetic corpus bytes must never be materialized'); },
              slice() { throw new Error('Synthetic corpus bytes must never be materialized'); },
              stream() { throw new Error('Synthetic corpus bytes must never be materialized'); },
            };
            const bytes = new Uint8Array(file.bytes).fill(file.seed);
            bytes.set(header.subarray(0, file.bytes));
            state.materializedBytes += bytes.length;
            return new File([bytes], file.name, { type: 'image/png', lastModified: 1_700_000_000_000 });
          },
        };
      };
      const children = (definition.folders ?? []).map(child => createDirectory(child, permission));
      return {
        kind: 'directory', name: definition.label,
        async queryPermission() { return permission.state; },
        async requestPermission() { return permission.state; },
        grant() { permission.state = 'granted'; },
        async *values(): AsyncGenerator<unknown> { for (let i = 0; i < count; i++) yield fileHandle(i); for (const child of children) yield child; },
        async getFileHandle(name: string) {
          const index = definition.files ? definition.files.findIndex(file => file.name === name) : Number(name.match(/\d+/)?.[0]);
          if (index < 0 || index >= count) throw new DOMException('File missing', 'NotFoundError');
          return fileHandle(index);
        },
        async getDirectoryHandle(name: string) {
          const child = children.find(directory => directory.name === name);
          if (!child) throw new DOMException('Directory missing', 'NotFoundError');
          return child;
        },
      };
    };
    // Fresh handle objects, permission state and generated bytes on every navigation.
    const handles = directories.map(definition => createDirectory(definition));
    Object.assign(window, { showDirectoryPicker: async () => {
      const handle = handles[state.next++ % handles.length]; handle.grant(); return handle;
    } });
  }, { directories, png });
}
