import type { BrowserContext } from '@playwright/test';

export type DirectoryFixture = {
  label: string;
  count?: number;
  metadataOnly?: boolean;
  files?: Array<{ name: string; bytes: number; seed: number }>;
};

/** Picker replacement exists only in the runner. No application hooks or auth bypass. */
export async function installDirectories(context: BrowserContext, directories: DirectoryFixture[], png: string) {
  await context.addInitScript(({ directories, png }) => {
    const state = { next: 0, metadataReads: 0, materializedBytes: 0, workers: 0, maxWorkers: 0, workerUrls: [] as string[] };
    Object.assign(window, { __directoryFixture: state });
    const NativeWorker = window.Worker;
    window.Worker = class extends NativeWorker {
      private ended = false;
      constructor(url: string | URL, options?: WorkerOptions) {
        super(url, options);
        state.workers++; state.maxWorkers = Math.max(state.maxWorkers, state.workers);
        state.workerUrls.push(String(url));
      }
      terminate() { if (!this.ended) { state.workers--; this.ended = true; } super.terminate(); }
    };
    const header = Uint8Array.from(atob(png), char => char.charCodeAt(0));
    const createDirectory = (definition: DirectoryFixture) => {
      let permission: PermissionState = 'prompt';
      const count = definition.count ?? definition.files!.length;
      const descriptor = (index: number) => definition.files?.[index] ?? {
        name: `photo-${String(index).padStart(6, '0')}.jpg`, bytes: 2 * 1024 * 1024, seed: index,
      };
      const fileHandle = (index: number) => {
        const file = descriptor(index);
        return {
          kind: 'file', name: file.name,
          async getFile() {
            if (permission !== 'granted') throw new DOMException('Directory permission lost', 'NotAllowedError');
            state.metadataReads++;
            if (definition.metadataOnly) return {
              name: file.name, size: file.bytes, type: 'image/jpeg', lastModified: 1_700_000_000_000,
              arrayBuffer() { throw new Error('Synthetic corpus bytes must never be materialized'); },
              slice() { throw new Error('Synthetic corpus bytes must never be materialized'); },
              stream() { throw new Error('Synthetic corpus bytes must never be materialized'); },
            };
            const bytes = new Uint8Array(file.bytes).fill(file.seed);
            bytes.set(header.subarray(0, file.bytes));
            state.materializedBytes += bytes.length;
            return new File([bytes], file.name, { type: 'image/png', lastModified: 1_700_000_000_000 });
          },
        };
      };
      return {
        kind: 'directory', name: definition.label,
        async queryPermission() { return permission; },
        async requestPermission() { return permission; },
        grant() { permission = 'granted'; },
        async *values() { for (let i = 0; i < count; i++) yield fileHandle(i); },
        async getFileHandle(name: string) {
          const index = definition.files ? definition.files.findIndex(file => file.name === name) : Number(name.match(/\d+/)?.[0]);
          if (index < 0 || index >= count) throw new DOMException('File missing', 'NotFoundError');
          return fileHandle(index);
        },
        async getDirectoryHandle() { throw new DOMException('Directory missing', 'NotFoundError'); },
      };
    };
    // Fresh handle objects, permission state and generated bytes on every navigation.
    const handles = directories.map(createDirectory);
    Object.assign(window, { showDirectoryPicker: async () => {
      const handle = handles[state.next++ % handles.length]; handle.grant(); return handle;
    } });
  }, { directories, png });
}
